TokenManager:
  bilibili:
    headers:
      'accept-language': zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
      'origin': https://www.bilibili.com
      'referer': https://space.bilibili.com/
      'origin_2': https://space.bilibili.com
      'cookie': enable_web_push=DISABLE; home_feed_column=5; buvid3=439EB233-5D03-3E32-702A-5CB95A60614A57594infoc; b_nut=1746851557; _uuid=DA41038CF-3493-316A-9286-496D10828BD4F58802infoc; buvid_fp=6a1c611c854369ca03f5d862a60b5c53; buvid4=BCCD7B4E-9E2C-5C30-35C7-A9C11235D75559256-025051012-LrJKfACCaN5Etm83DIndjg%3D%3D; rpdid=|(u)~RmRYYlJ0J'u~RY)lulYu; DedeUserID=1563114089; DedeUserID__ckMd5=91afdf8c568682bd; hit-dyn-v2=1; theme-tip-show=SHOWED; CURRENT_QUALITY=80; theme-avatar-tip-show=SHOWED; bili_ticket=eyJhbGciOiJIUzI1NiIsImtpZCI6InMwMyIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Njk1MjgwNzIsImlhdCI6MTc2OTI2ODgxMiwicGx0IjotMX0.N2KXGNLn5S_QFZZj58V8EV2dGZPCEybouNaB91qyJ-I; bili_ticket_expires=1769528012; SESSDATA=3a77568c%2C1784820876%2Ccc42a%2A12CjAgwvze_bIEGCubHTQsjilhyU6g7e8X-woKceShqMcTFL0nuFLg0disjgJ4T3m7_EYSVlh0WVZRX1p3RzlNR1hjVDhCN3RRR1BIbHJnNnB0aTZLN1d0SVhmNEF5ako3Q1ZNMTdWRjNLVjVlT1dKZTc2aEo5czAwbndNMHlxYkR2M1dEcG51ckFBIIEC; bili_jct=62972033c7b3800315efeb4aa4749e67; bp_t_offset_1563114089=1161498846354735104; sid=4j9ozc73; browser_resolution=1528-324; CURRENT_FNVAL=4048; b_lsid=E5055189_19BF0C49CD5
      'user-agent': Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

    proxies:
      http:
      https: